#!/usr/bin/env bash

main () {
    input="$1"
    result=""

    for (( i=${#input}-1; i>=0; i-- ))
    do
        result+="${input;i:1}"
    done

    echo "$result"
}

main "$@"

# Get first parameter
#input="$1"

# Get length of string
#input_length=${#input}

# Access characters by index
#${var:index:length}